############################################################
#                                                          #
#                  COVID-19 ZA dataframe                   #
#                                                          #
############################################################

#-- Historical data from the NICD: 2020-03-11 to 2020-03-14 --#
# date <- c(rep('2020-03-12', 9),
#           rep('2020-03-13', 9),
#           rep('2020-03-14', 9))
# 
# provinces <- c(rep(c('FS',
#                      'EC',
#                      'GP',
#                      'KZN',
#                      'LP',
#                      'MP',
#                      'NW',
#                      'NC',
#                      'WC'), 3))
# 
# n_cases <- c(c('FS' = 0,
#                'EC' = 0,
#                'GP' = 6,
#                'KZN' = 8,
#                'LP' = 0,
#                'MP' = 1,
#                'NW' = 0,
#                'NC' = 0,
#                'WC' = 1),
#              c('FS' = 0,
#                'EC' = 0,
#                'GP' = 10,
#                'KZN' = 10,
#                'LP' = 0,
#                'MP' = 1,
#                'NW' = 0,
#                'NC' = 0,
#                'WC' = 3),
#              c('FS' = 0,
#                'EC' = 0,
#                'GP' = 17,
#                'KZN' = 11,
#                'LP' = 0,
#                'MP' = 1,
#                'NW' = 0,
#                'NC' = 0,
#                'WC' = 9))
# 
# n_deaths <- c(c('FS' = 0,
#                 'EC' = 0,
#                 'GP' = 0,
#                 'KZN' = 0,
#                 'LP' = 0,
#                 'MP' = 0,
#                 'NW' = 0,
#                 'NC' = 0,
#                 'WC' = 0),
#               c('FS' = 0,
#                 'EC' = 0,
#                 'GP' = 0,
#                 'KZN' = 0,
#                 'LP' = 0,
#                 'MP' = 0,
#                 'NW' = 0,
#                 'NC' = 0,
#                 'WC' = 0),
#               c('FS' = 0,
#                 'EC' = 0,
#                 'GP' = 0,
#                 'KZN' = 0,
#                 'LP' = 0,
#                 'MP' = 0,
#                 'NW' = 0,
#                 'NC' = 0,
#                 'WC' = 0))
#
# n_recoveries <- c(c('FS' = 0,
#                 'EC' = 0,
#                 'GP' = 0,
#                 'KZN' = 0,
#                 'LP' = 0,
#                 'MP' = 0,
#                 'NW' = 0,
#                 'NC' = 0,
#                 'WC' = 0),
#               c('FS' = 0,
#                 'EC' = 0,
#                 'GP' = 0,
#                 'KZN' = 0,
#                 'LP' = 0,
#                 'MP' = 0,
#                 'NW' = 0,
#                 'NC' = 0,
#                 'WC' = 0),
#               c('FS' = 0,
#                 'EC' = 0,
#                 'GP' = 0,
#                 'KZN' = 0,
#                 'LP' = 0,
#                 'MP' = 0,
#                 'NW' = 0,
#                 'NC' = 0,
#                 'WC' = 0))
# 
# n_tests <- c(rep(848, 9),
#              rep(924, 9),
#              rep(1017, 9))
# 
# data <- data.frame(date = date,
#                    provinces = provinces,
#                    n_tests = n_tests,
#                    n_cases = n_cases,
#                    n_deaths = n_deaths,
#                    n_recoveries = n_recoveries)
# 
# write.csv(data, file = 'data.csv', row.names = FALSE)

data <- read.csv('data.csv', stringsAsFactors = FALSE)

# NB: Check date
data <- tibble::add_row(.data = data,
                        date = as.character(rep(Sys.Date(), 10)),
                        provinces = c('EC',
                                      'FS', 
                                      'GP',
                                      'KZN',
                                      'LP',
                                      'MP',
                                      'NC',
                                      'NW',
                                      'WC',
                                      'Unknown'),
                        n_tests = rep(41072, 10),
                        n_cases = c('EC' = 12,
                                    'FS' = 74, 
                                    'GP' = 633,
                                    'KZN' = 179,
                                    'LP' = 14,
                                    'MP' = 12,
                                    'NC' = 6,
                                    'NW' = 8,
                                    'WC' = 325,
                                    'Unknown' = 90),
                        n_deaths = c('EC' = 0,
                                     'FS' = 1, 
                                     'GP' = 1,
                                     'KZN' = 2,
                                     'LP' = 0,
                                     'MP' = 0,
                                     'NC' = 0,
                                     'NW' = 0,
                                     'WC' = 1,
                                     'Unknown' = 0),
                        n_recoveries = c('EC' = 0,
                                         'FS' = 0, 
                                         'GP' = 0,
                                         'KZN' = 0,
                                         'LP' = 0,
                                         'MP' = 0,
                                         'NC' = 0,
                                         'NW' = 0,
                                         'WC' = 0,
                                         'Unknown' = 4))

write.csv(data, file = 'data.csv', row.names = FALSE)


